services:
  - type: web
    name: model-c2-amr-emulator
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: SIMULATION_START
        value: 2026-05-11T15:00:44.959Z
